# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c26071c607962535b74ec8b5413b4727a9f4c8c1764c8e6a4773500455f859baeae4141110017b089c7bb075d5e8a0b3c94d23e816a55e4e02541848f8d3f59c

test:
  secret_key_base: 42b8ba1313ca9aef8ad98548234884010d7a95f4d8e16767da340e7e9685acb169e681eff58894ed0262771af1ca70c23eaef12aaa9dab4648e142dfdeb7d4a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
